package ui

// This file is the main editing point for Selene's TUI copy. Keep interface
// wording here so contributors can revise tone without touching state logic.

const (
	textTagline = "There are truths that only the light of the moon can reveal."

	textActivityDoctor                    = "Checking the environment without changing any files..."
	textActivityDetails                   = "Loading installation details without applying changes..."
	textActivityFetch                     = "Downloading, checking SHA-256, and inspecting packages..."
	textActivityInstallPreview            = "Preparing the installation confirmation..."
	textActivityRollbackPreview           = "Looking for snapshots that can be restored..."
	textActivityRemovePreview             = "Looking for every managed LuaTools integration file..."
	textActivityDetailsRefresh            = "Refreshing installation details without applying changes..."
	textActivityFetchRefresh              = "Checking cached artifacts again..."
	textActivityInstall                   = "Installing with an active snapshot. Do not close Selene..."
	textActivityRollback                  = "Restoring the snapshot and restarting Steam. Do not close Selene..."
	textActivityRemove                    = "Removing with a safety snapshot. Do not close Selene..."
	textActivitySteamGames                = "Scanning Steam libraries and linked game folders..."
	textActivityAnalyzeGame               = "Inspecting the selected game without changing its files..."
	textActivityFixPlatformAssetOverride  = "Disabling the PlatformAssetOverrides plugin with a safety snapshot..."
	textActivityUndoPlatformAssetOverride = "Restoring the PlatformAssetOverrides plugin from its safety snapshot..."
	textActivityScanCompatdata            = "Scanning NTFS libraries for Proton compatdata..."
	textActivityConfigureCompatdata       = "Configuring Proton compatdata on a native filesystem..."
	textActivityRollbackCompatdata        = "Restoring the original NTFS compatdata backup..."
	textActivityCloseSteam                = "Closing Steam safely before the selected operation..."
	textActivityRepairNTFSMount           = "Remounting NTFS with case-preserving filenames for this session..."

	textFooterHome                            = "↑/↓ navigate  •  enter select  •  esc back  •  q quit"
	textFooterDoctor                          = "↑/↓ scroll  •  r check again  •  esc back  •  q quit"
	textFooterDetails                         = "↑/↓ scroll  •  r refresh  •  esc back  •  q quit"
	textFooterFetch                           = "↑/↓ scroll  •  r verify cache  •  esc back  •  q quit"
	textFooterInstallConfirm                  = "↑/↓ scroll  •  i install  •  esc cancel"
	textFooterRollbackConfirm                 = "↑/↓ scroll  •  d restore  •  esc cancel"
	textFooterRemoveConfirm                   = "↑/↓ scroll  •  x remove completely  •  esc cancel"
	textFooterPlugins                         = "↑/↓ navigate  •  enter select  •  esc back  •  q quit"
	textFooterPlatformAssetOverride           = "↑/↓ select  •  enter inspect  •  esc back"
	textFooterPlatformAssetOverrideDetails    = "↑/↓ scroll  •  f fix  •  esc back  •  q quit"
	textFooterPlatformAssetOverrideFixConfirm = "↑/↓ scroll  •  f apply fix  •  esc cancel"
	textFooterPlatformAssetOverrideFixResult  = "↑/↓ scroll  •  u undo fix  •  esc back"
	textFooterCompatdata                      = "↑/↓ select  •  enter view plan  •  esc back"
	textFooterCompatdataPlan                  = "↑/↓ scroll  •  esc back"
	textFooterCompatdataPlanConfigure         = "↑/↓ scroll  •  c configure  •  esc cancel"
	textFooterCompatdataPlanRollback          = "↑/↓ scroll  •  r restore  •  esc cancel"
	textFooterCompatdataPlanRepair            = "↑/↓ scroll  •  f fix this session  •  m manual steps  •  c compatdata anyway  •  esc back"
	textFooterCompatdataSteamConfirm          = "↑/↓ scroll  •  c close Steam and continue  •  esc cancel"
	textFooterCompatdataNTFSManual            = "↑/↓ scroll  •  esc back"
	textFooterCompatdataNTFSResult            = "↑/↓ scroll  •  m manual steps  •  esc back"
	textFooterResult                          = "↑/↓ scroll  •  esc back  •  q quit"
	textFooterTransaction                     = "Transaction in progress • wait for commit or automatic rollback"

	textNoDiagnostics       = "No diagnostic has been run yet."
	textDoctorTitle         = "Environment check"
	textDoctorSummaryFormat = "%d passed • %d warning(s) • %d error(s) • r check again"

	textDetailsTitle       = "Installation details"
	textNoDetails          = "No installation details are available."
	textCatalogLabel       = "Catalog "
	textDetailsReady       = "✓ This environment is ready to install"
	textDetailsBlocked     = "! This installation still has blockers"
	textProposedOperations = "Proposed operations:"
	textNoChangesRefresh   = "No changes were applied. Press r to refresh."

	textArtifactsTitle         = "LuaTools artifacts"
	textVerifiedArtifactsTitle = "Verified artifacts"
	textNoArtifacts            = "No verified artifacts."
	textDownloadedNow          = "downloaded now"
	textAlreadyCached          = "already in cache"
	textCacheLabel             = "cache: "
	textCacheOnly              = "These files are only cached; nothing was installed."

	textInstallConfirmTitle = "Confirm installation"
	textInstallBlocked      = "× This environment cannot run the installation yet."
	textBeforeContinue      = "Before you continue"
	textInstallBulletSteam  = "• Steam and Lumen will be stopped by the verified installer."
	textInstallBulletSource = "• setup.sh comes from the pinned ZIP and is checked with SHA-256."
	textInstallBulletScope  = "• Sudo and /usr changes are blocked; everything stays in your user account."
	textInstallBulletBackup = "• A persistent snapshot is created before the first change."
	textInstallBulletFail   = "• Any failure triggers automatic rollback and restarts Steam."
	textInstallAction       = "Press i to install."
	textEscapeNoChanges     = "Esc cancels without changing anything."

	textInstallResultTitle = "Installation result"
	textInstalled          = "✓ LuaTools installed"
	textTransactionLabel   = "Transaction: "
	textSnapshotRetained   = "The snapshot was kept; use Undo last installation if needed."
	textOperationLog       = "Operation log:"

	textRollbackTitle         = "Undo last installation"
	textNoRollback            = "No restorable snapshot was found."
	textRollbackExplanation   = "Selene will stop Steam and the guardian, restore every tracked file, then start Steam again."
	textRollbackAction        = "Press d to restore."
	textRecoveryTitle         = "Recover interrupted removal"
	textRecoveryExplanation   = "The removal did not finish. Selene will restore the installed stack from its safety snapshot and restart Steam."
	textRecoveryAction        = "Press d to recover."
	textSnapshotLabel         = "Snapshot: "
	textCreatedLabel          = "Created: "
	textOperationLabel        = "Operation: "
	textEscapeKeepsInstall    = "Esc keeps the current installation."
	textRollbackResultTitle   = "Rollback result"
	textPreviousStateRestored = "✓ Previous state restored and Steam restarted"

	textRemoveTitle            = "Remove LuaTools completely"
	textNoManagedTraces        = "No managed LuaTools, Lumen, or slsteam-moon files were found."
	textRemoveIsDifferent      = "This is different from undoing the last installation."
	textRemoveScope            = "It removes LuaTools, Lumen, slsteam-moon, settings, services, and Steam integration from your user account. Internal plugin data is deleted too."
	textRemoveKeeps            = "It does not remove your games, Steam, Selene, the download cache, or safety snapshots."
	textDetectedTraces         = "Detected files:"
	textRemoveSafety           = "Selene creates another snapshot first and restores the installed state if anything fails."
	textRemoveAction           = "Press x to remove completely."
	textRemoveResultTitle      = "Complete removal result"
	textRemoved                = "✓ LuaTools integration removed"
	textRemovedExplanation     = "LuaTools, Lumen, and slsteam-moon are no longer integrated with Steam."
	textSafetyTransactionLabel = "Safety transaction: "
	textNothingRemoved         = "No managed installation was found; nothing changed."

	textPluginsTitle            = "Selene Plugins"
	textSteamLibrarySourceLabel = "Library: "
	textSteamLibraryMountLabel  = "Mounted disk: "

	textPlatformAssetOverrideTitle            = "Fix PlatformAssetOverrides"
	textPlatformAssetOverrideIntro            = "Choose a Steam-managed game to inspect for Unreal, Unity, and PlatformAssetOverrides files. This inspection does not change game files."
	textNoSteamGames                          = "No installed Steam games were found in the configured or Selene-linked libraries."
	textSteamGameMetadataFormat               = "App %s · library: %s"
	textPlatformAssetOverrideSelectHint       = "Press Enter to inspect the selected game before any repair is considered."
	textPlatformAssetOverrideAnalysisTitle    = "PlatformAssetOverrides analysis"
	textNoPlatformAssetOverrideAnalysis       = "No game analysis is available."
	textSteamGamePathLabel                    = "Game: "
	textDetectedEngineLabel                   = "Detected engine: "
	textDetectedEngineUnreal                  = "Unreal Engine"
	textDetectedEngineUnity                   = "Unity"
	textDetectedEngineUnknown                 = "not identified"
	textPlatformPluginFound                   = "! PlatformAssetOverrides plugin descriptor found"
	textPlatformPluginReferenced              = "! PlatformAssetOverrides is referenced by the game project"
	textPlatformPluginNotFound                = "No PlatformAssetOverrides descriptor or project reference was found."
	textUnityAssetsFound                      = "Unity resources.assets file(s) found:"
	textPlatformAssetOverrideSafety           = "Selene did not replace assets, disable a plugin, or add a module. A missing Unreal module needs a game-version-compatible repair; a generic asset link would be unsafe."
	textPlatformAssetOverrideVerifyHint       = "First use Steam Properties → Installed Files → Verify integrity. Selene can automate a repair only after its exact compatible source is known."
	textPlatformAssetOverrideFixAction        = "Press f to disable the PlatformAssetOverrides plugin."
	textPlatformAssetOverrideFixConfirmTitle  = "Confirm PlatformAssetOverrides fix"
	textPlatformAssetOverrideFixIntro         = "This Unreal game references the PlatformAssetOverrides plugin, which fails to load on Linux. Selene will rename the plugin descriptor so Unreal skips it."
	textPlatformAssetOverrideFixSafety        = "Only the plugin descriptor is renamed; no game assets are replaced. A safety snapshot is created first so the fix can be undone."
	textPlatformAssetOverrideFixConfirmAction = "Press f to apply the fix."
	textPlatformAssetOverrideFixResultTitle   = "PlatformAssetOverrides fix result"
	textNoPlatformAssetOverrideFix            = "No fix result is available."
	textPlatformAssetOverrideFixed            = "✓ PlatformAssetOverrides plugin disabled"
	textDisabledDescriptorLabel               = "Disabled descriptor: "
	textPlatformAssetOverrideFixResultHint    = "Press u to undo the fix and restore the original plugin descriptor."

	textCompatdataTitle               = "NTFS Proton compatdata link"
	textCompatdataIntro               = "Move Proton prefixes off NTFS to a native Linux filesystem while games stay shared on the NTFS disk. Each NTFS library gets its own compatdata directory."
	textNTFSDualBootOnlyNotice        = "This NTFS feature is intended only for dual-boot users who need to share a game library between Windows and Linux. If the library is used only on Linux, Selene recommends Btrfs or Ext4 instead."
	textNTFSWindowsSystemDiskWarning  = "Selene does not recommend linking a Steam library from the Windows system partition (usually C:). Prefer a separate partition dedicated to games, keeping Windows system files isolated from the shared library."
	textNoCompatdataLibraries         = "No NTFS Steam libraries were found."
	textCompatdataMetadataFormat      = "%s · mounted at %s"
	textCompatdataStateLabel          = "State: "
	textCompatdataSelectHint          = "Press Enter to review the setup plan before any change."
	textCompatdataPlanTitle           = "Compatdata setup plan"
	textNoCompatdataPlan              = "No setup plan was selected."
	textCompatdataCurrentLabel        = "Current compatdata: "
	textCompatdataExistingLinkLabel   = "Existing link: "
	textCompatdataImportSourceLabel   = "Existing link target: "
	textCompatdataTargetLabel         = "Native target: "
	textCompatdataPreservedLabel      = "Preserved native copy: "
	textCompatdataBackupLabel         = "Backup: "
	textCompatdataBlockedLabel        = "Blocked: "
	textCompatdataWillCopy            = "Selene will copy the existing compatdata, back up the original, then create a symlink to the native target."
	textCompatdataWillLink            = "Selene will create the native target and a symlink to it."
	textCompatdataWillImportLink      = "Selene will copy prefixes from the existing manual link target, detach that link, then create a managed link to the native target."
	textCompatdataWillReplaceBroken   = "Selene will detach the broken manual link, then create a managed link to the native target."
	textCompatdataWillRecoverRollback = "Selene found native prefix data preserved by an earlier rollback. It will archive that copy with an atomic rename, refresh the native target from the current compatdata, then recreate the managed link."
	textCompatdataSafety              = "No files are deleted. The original compatdata stays as a backup, and games remain on the NTFS disk."
	textCompatdataRecoverySafety      = "The earlier native copy remains available at the preserved path. Selene does not merge conflicting prefix trees or require manual cleanup."
	textCompatdataManualLinkSafety    = "The previous link is saved in the safety transaction and its target is never deleted. Rollback restores the exact previous link."
	textCompatdataConfigureAction     = "Press c to configure Proton compatdata."
	textCompatdataReplaceLinkAction   = "Press c to safely replace the existing compatdata link."
	textCompatdataCannotConfigure     = "Selene cannot change this library automatically without risking existing data."
	textCompatdataAlreadyManaged      = "This is an existing Selene-managed compatdata link."
	textCompatdataRollbackAction      = "Press r to restore the previous compatdata setup."
	textCompatdataRollbackSafety      = "The native target is archived automatically and no prefix data is deleted."
	textCompatdataNoRollback          = "Selene recognised the link, but no unambiguous backup is available for automatic rollback."
	textCompatdataResultTitle         = "Compatdata setup result"
	textNoCompatdataResult            = "No setup result is available."
	textCompatdataConfigured          = "✓ Proton compatdata configured on a native filesystem"
	textCompatdataAlreadyConfigured   = "✓ Compatdata was already configured"
	textCompatdataRolledBack          = "✓ Previous compatdata setup restored"
	textCompatdataSourceLabel         = "Compatdata link: "
	textCompatdataResultHint          = "The original NTFS compatdata remains as a backup. Use Undo to restore it if needed."
	textCompatdataManualResultHint    = "The previous manual link target was preserved. Selene can restore that exact link through rollback."
	textCompatdataRollbackResultHint  = "The managed link was removed and the previous compatdata setup was restored. The native prefix tree was archived automatically, leaving the target ready for a future setup."
	textCompatdataRecoveryResultHint  = "The earlier rollback copy was archived automatically and the current compatdata was configured on a clean native target."

	textCompatdataSteamConfirmTitle    = "Close Steam to continue"
	textCompatdataSteamDetected        = "Steam is currently running. Selene will not change compatdata while the client can still write Proton prefixes."
	textCompatdataSteamConfigureReason = "Steam must be closed before Selene configures the managed compatdata link."
	textCompatdataSteamRestoreReason   = "Steam must be closed before Selene restores the previous compatdata setup."
	textCompatdataSteamRemountReason   = "Steam must be closed before Selene temporarily remounts the NTFS game disk."
	textCompatdataSteamCloseBehavior   = "Selene will request a clean shutdown for Steam processes owned by your user and wait for them to exit. After the grace period, remaining Steam processes will be force-closed. The compatdata operation starts only after every Steam process has stopped."
	textCompatdataSteamCloseAction     = "[ c ] Close Steam and continue"

	textNTFSFilenameStatusLabel        = "Filename compatibility: "
	textNTFSDeviceLabel                = "NTFS device: "
	textNTFSDriverLabel                = "Mount driver: "
	textNTFSForcedLowercaseWarning     = "× This mount forces Steam filenames to lowercase"
	textNTFSForcedLowercaseExplanation = "Games that validate the original spelling of scripts, textures, or assets can show missing or corrupted graphics. Moving compatdata alone does not fix game files exposed this way."
	textNTFSFilenameUnknown            = "! Selene could not verify whether this NTFS mount preserves filename spelling. No automatic remount will be offered."
	textNTFSSessionRepairAction        = "[ f ] Fix filename handling for this session"
	textNTFSSessionRepairScope         = "This temporary repair closes Steam first; the volume is never force-unmounted. The operating system may restore its previous policy after reboot."
	textNTFSManualAction               = "[ m ] Show manual steps"
	textNTFSSteamDetected              = "Steam is currently running. Selene will not unmount a game disk while the client can still access its libraries."
	textNTFSSteamCloseBehavior         = "Selene will close Steam processes owned by your user, unmount the exact NTFS device without force, remount it with case-preserving names, and verify the result before reporting success."

	textNTFSManualTitle           = "Manual NTFS filename fix"
	textNTFSManualIntro           = "Use these commands only after closing Steam and every application using this disk. They reproduce Selene's temporary session repair without changing /etc or using sudo."
	textNTFSManualDeviceLabel     = "Device: "
	textNTFSManualMountLabel      = "Mount point: "
	textNTFSManualStepClose       = "1. Close Steam completely. Then run:"
	textNTFSManualUnmountFormat   = "udisksctl unmount -b %s"
	textNTFSManualMountFormat     = "udisksctl mount -b %s -t ntfs -o rw,noatime,uid=$(id -u),gid=$(id -g),umask=0022,windows_names,big_writes"
	textNTFSManualVerify          = "2. Verify that the mount process uses mount.ntfs and does not contain ignore_case. Then open Steam through the SLSsteam/LuaTools launcher."
	textNTFSManualPersistence     = "This correction is temporary. Rebooting or remounting through the desktop may restore the distribution's default options."
	textNTFSManualNoForce         = "Never add --force when the volume is busy. Close the process using the disk and retry."
	textNTFSManualBazziteTitle    = "Persistent Bazzite policy (manual)"
	textNTFSManualBazziteIntro    = "Bazzite currently adds ignore_case through its NTFS automount policy. To keep case-preserving names after reboot, open the policy file manually:"
	textNTFSManualBazziteCommand  = "sudoedit /etc/default/steamos-btrfs"
	textNTFSManualBazziteEdit     = "In STEAMOS_BTRFS_SDCARD_NTFS_MOUNT_OPTS, remove only the ignore_case item. Keep the remaining options, save, then reboot or safely remount the disk."
	textNTFSManualBazziteBoundary = "This changes a system-wide distribution policy and is intentionally outside Selene's user-only automation. Back up important NTFS data first; Bazzite still does not officially support gaming from NTFS."

	textNTFSResultTitle          = "NTFS filename repair result"
	textNTFSNoResult             = "No NTFS remount result is available."
	textNTFSResultConfigured     = "✓ NTFS filenames are case-preserving for this session"
	textNTFSResultTemporary      = "No game files or system configuration were changed. This mount policy lasts only until the disk is remounted or the system restarts."
	textNTFSResultOpenSteam      = "Open Steam through the SLSsteam/LuaTools launcher, then test the affected game."
	textNTFSResultRecoveredMount = "Selene attempted to restore the operating system's default mount after the repair failed. Review the error before trying the manual steps."

	textAboutTitle  = "About Selene"
	textAboutBody   = "Selene is an independent community manager that makes the\nLuaTools ecosystem accessible on Linux. Its priority is to install,\ncheck, update, undo, and remove changes safely."
	textAboutState  = "Current state: transactional user-only install, rollback, and complete removal."
	textAboutAuthor = "Created by YlanzinhoY."
)

var textHomeMenu = []menuItem{
	{title: "Check compatibility", description: "Check Linux, Steam, libraries, and Proton"},
	{title: "Installation details", description: "Review downloads and changes before installing"},
	{title: "Download and verify", description: "Cache verified packages without installing them"},
	{title: "Install LuaTools", description: "Use verified sources with an automatic snapshot and rollback"},
	{title: "Undo last installation", description: "Restore the exact previous state and restart Steam"},
	{title: "Remove LuaTools completely", description: "Remove LuaTools, Lumen, and slsteam-moon from your user account"},
	{title: "Selene Plugins", description: "Explore optional community tools that remain safe and user-scoped"},
	{title: "About Selene", description: "Learn about the project's mission and current status"},
	{title: "Exit", description: "Close the interface"},
}

func defaultMenuItems() []menuItem {
	return append([]menuItem(nil), textHomeMenu...)
}

var textPluginMenu = []menuItem{
	{title: "NTFS Compatdata Link", description: "Move Proton prefixes off NTFS to a native Linux filesystem"},
	{title: "Fix PlatformAssetOverrides", description: "Find a Steam game and inspect this Unreal or Unity compatibility error"},
}

func defaultPluginItems() []menuItem {
	return append([]menuItem(nil), textPluginMenu...)
}
